name: tutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
      - scikit-learn==0.23.2
      - mlflow>=1.0
      - pandas
      - boto3
      - git+https://github.com/ncsa/mlflow-slurm.git@initial
   
